environment:
  map:
    image: assets/big_map.png
    graph: assets/big_map.pickle
    pixel_to_cm: 1
  max_timesteps: 500
sensors:
  - type: Line
    name: Line A
  - type: Line
    name: Line B

adversaries:
  - radius: 10
    speed: 5
